def Deployer = null

node {
	stage( "Checkout" ) {
		checkout scm
		Deployer = load( "Deployer.groovy" )
	}
	
	stage( "Build" ) {
		sh( "docker build --tag whole-pipeline ." )
	}
	
	stage( "Test" ) {
		try {
			sh( "docker run --entrypoint python whole-pipeline -m unittest discover" )
		} catch( Exception e ) {
			slackSend(
				color: 'error',
				message: 'whole-pipeline unit tests failed.' )
			throw e
		}
	}
	
	stage( "Push" ) {
		sh( "docker push whole-pipeline" )
	}
	
	stage( "Deploy to TEST" ) {
		Deployer.deploy( "test" )
	}
	
	if( BRANCH_NAME == "master" ) {
		stage( "Deploy to PRODUCTION" ) {
			Deployer.deploy( "production" )
		}
	}
}
