name: Tests

on:
  push:
    branches-ignore:
      "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up GPG
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: printf '${GPG_KEY}' | gpg --import
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Dependencies
      run: mvn --batch-mode dependency:go-offline -Pit
    - name: Build & Test with Maven
      run: mvn --batch-mode verify -Pit -Dgpg.passphrase='${{ secrets.GPG_PASSPHRASE }}'
