name: Tests

on:
  push:
    branches-ignore:
      "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up GPG
      run: echo "${{ secrets.GPG_KEY_BASE64 }}" | base64 --decode | gpg --import && gpg --list-keys
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Dependencies
      run: mvn --batch-mode dependency:go-offline -Pit
    - name: Build & Test with Maven
      run: mvn --batch-mode verify -Pit -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
